name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false

    # ssh setup
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Get dependencies
      run: sudo apt update && sudo apt install libwayland-dev libxkbcommon-dev xorg-dev make -y
    
    - name: Init and update submodules
      run: |
        git submodule init
        git submodule update --recursive

    - name: Run make
      run: make

    - name: clean
      run: make fclean