name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get dependencies
      run: sudo apt update && sudo apt install libwayland-dev libxkbcommon-dev xorg-dev make -y
    
    - name: Run make
      run: ./install/install_deps.sh && make

    - name: clean
      run: make fclean
